
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: QATestAssignment_Database

test:
  <<: *default
  database: QATestAssignment_test


# production:
#   <<: *default
#   database: QATestAssignment_production
#   username: QATestAssignment
#   password: <%= ENV['QATESTASSIGNMENT_DATABASE_PASSWORD'] %>
